### ISSUE TITLE
json-patch-duplex.js error

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/KitchenSink#162] opened 2017-07-31 12:24 UTC
In order to reproduce, follow these steps:
![errorks](https://user-images.githubusercontent.com/8951553/28777510-b3433c2c-75fb-11e7-8ed1-66dfd149c3dc.gif)

`observer` is `undefined` and `beforeDict` is an empty array.

**Comment by PatrykSzwer** [comment] 2017-11-27 09:26
I couldn't reproduce this. I'll close this issue for now, as unreproducible, and if You get this error again, please reopen and make more detailed steps to reproduce.

**Closed by PatrykSzwer** 2017-11-27 09:26 UTC
