### ISSUE TITLE
KitchenSink doesn't seem to work on 2.3.1.7034

### ISSUE THREAD

**Issue by RickardR** [Starcounter/KitchenSink#165] opened 2017-08-22 14:07 UTC
And a couple of versions prior to that. Think it has something to do with the breaking changes with slots etc....Just a blank page, Json can be viewed through debug-aid though, so stuff just isn't rendered/bound.
Hade 7012 before that, there it worked.

**Comment by PatrykSzwer** [comment] 2017-08-23 08:36
Are you using master branch o KitchenSink? Because master branch is checked to be compatible with current stable version of Starcounter (right now, 2.3.0.6350), when develop branch is version compatible with newest candidates of SC. Please always try version from develop branch, when You're using one of the candidate versions of Starcounter.

**Comment by PatrykSzwer** [comment] 2017-11-27 09:13
Since It's no longer reproducible, I'll close this issue. Feel free to reopen if problem still occurs.

**Closed by PatrykSzwer** 2017-11-27 09:13 UTC
